services:
  # server:
  #   build:
  #     context: ./server
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - shared_volume:/app/shared
  #   environment:
  #   - BACKEND_PORT=8080
  #   - FRONTEND_PORT=8081

  # client_mobile:
  #   build:
  #     context: ./mobile
  #   volumes:
  #     - shared_volume:/apk
  #   depends_on:
  #     - server

  client_web:
    build:
      context: ./web
    ports:
      - "8081:8081"
    volumes:
      - shared_volume:/apk
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - PORT=8081

volumes:
  shared_volume:
