services:
  server:
    build:
      context: ./server
    volumes:
      - shared_volume:/apk
    ports:
      - "8080:8080"
    environment:
    - BACKEND_PORT=8080
    - FRONTEND_PORT=8081
    command: ["npm", "start"]

  client_mobile:
    build:
      context: ./mobile
    volumes:
      - shared_volume:/apk
    depends_on:
      - server

  client_web:
    build:
      context: ./web
    ports:
      - "8081:8081"
    volumes:
      - shared_volume:/apk
    depends_on:
      - server
      - client_mobile
    environment:
      - PORT=8081
      - BACKEND_PORT=8080
    command: ["npm", "start"]

volumes:
  shared_volume:
