name: Format Check

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check code formatting with Prettier (Frontend - Web)
        run: |
          cd web && npx prettier --check .

      - name: Check code formatting with Prettier (Backend - Server)
        run: |
          cd server && npx prettier --check .

      - name: Lint code with ESLint (Frontend - Web)
        run: |
          cd web && npx eslint . --ext .ts,.tsx
  
      - name: Lint code with ESLint (Backend - Server)
        run: |
          cd server && npx eslint . --ext .ts
